project:
  type: website

website:
  title: "Evelyn Yi Tsing Ng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Projects.qmd

  page-footer:
    right: "© Copyright 2024 Evelyn Ng."
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto
